ALTER TABLE "Shop"
ADD COLUMN "fulfillmentMode" TEXT NOT NULL DEFAULT 'DELIVERY',
ADD COLUMN "shippingFeeCents" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "shippingPolicy" TEXT,
ADD COLUMN "returnPolicy" TEXT;

ALTER TABLE "Shop" ALTER COLUMN "fulfillmentMode" SET DEFAULT 'PICKUP';

ALTER TABLE "Order"
ADD COLUMN "fulfillmentMode" TEXT NOT NULL DEFAULT 'DELIVERY',
ADD COLUMN "shippingFeeCents" INTEGER NOT NULL DEFAULT 0;
