ALTER TABLE "Shop" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'AED';

ALTER TABLE "Order" ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "Order" ALTER COLUMN "currency" SET DEFAULT 'AED';
